#!/usr/bin/env python3
"""Offline GLSL -> SPIR-V using an already installed libshaderc. No network."""
import ctypes as c
import ctypes.util
from pathlib import Path
s=c.CDLL(ctypes.util.find_library('shaderc') or 'libshaderc.so.1')
s.shaderc_compiler_initialize.restype=c.c_void_p
s.shaderc_compile_into_spv.argtypes=[c.c_void_p,c.c_char_p,c.c_size_t,c.c_int,c.c_char_p,c.c_char_p,c.c_void_p]
s.shaderc_compile_into_spv.restype=c.c_void_p
for name,restype in [('shaderc_result_get_compilation_status',c.c_int),('shaderc_result_get_error_message',c.c_char_p),('shaderc_result_get_length',c.c_size_t),('shaderc_result_get_bytes',c.c_void_p)]:
 f=getattr(s,name); f.argtypes=[c.c_void_p]; f.restype=restype
s.shaderc_result_release.argtypes=[c.c_void_p]; s.shaderc_compiler_release.argtypes=[c.c_void_p]
root=Path(__file__).resolve().parents[1]
compiler=s.shaderc_compiler_initialize()
if not compiler: raise RuntimeError('shaderc init failed')
try:
 for stage,kind in [('vert',0),('frag',1)]:
  p=root/'shaders'/f'sprite.{stage}'; source=p.read_bytes()
  result=s.shaderc_compile_into_spv(compiler,source,len(source),kind,str(p).encode(),b'main',None)
  if not result: raise RuntimeError('shaderc compile failed')
  try:
   if s.shaderc_result_get_compilation_status(result): raise RuntimeError(s.shaderc_result_get_error_message(result).decode())
   blob=c.string_at(s.shaderc_result_get_bytes(result),s.shaderc_result_get_length(result)); p.with_suffix(p.suffix+'.spv').write_bytes(blob)
   print(p.name,len(blob),'bytes')
  finally: s.shaderc_result_release(result)
finally: s.shaderc_compiler_release(compiler)
header=['// Generated by scripts/compile_shaders.py; do not edit.','#pragma once']
for stage in ['vert','frag']:
 data=(root/'shaders'/f'sprite.{stage}.spv').read_bytes()
 header.append('static const unsigned char sprite_'+stage+'_spv[] = {'+','.join(map(str,data))+'};')
(root/'native'/'src'/'shaders_spv.h').write_text('\n'.join(header)+'\n')
